import { type AnyPgColumn, pgTable, uuid, text, timestamp, jsonb, index, integer } from "drizzle-orm/pg-core";
import { companies } from "./companies.js";
import { pipelineTemplates } from "./pipeline_templates.js";
import { agents } from "./agents.js";

/**
 * Pipeline runs track active and historical executions of a pipeline template.
 * The pipeline service drives the state machine: pending → running → (completed | failed | cancelled).
 *
 * Each run stores:
 * - Which template it's based on
 * - Input context (spec content, idea, brand docs)
 * - Skill plan generated by the skill planner
 * - Eval results (scores, patterns, threshold adjustments)
 * - Overall status and timing
 */
export const pipelineRuns = pgTable(
  "pipeline_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id, { onDelete: "cascade" }),
    templateId: uuid("template_id").notNull().references(() => pipelineTemplates.id),

    /** Human-readable label for this run (e.g. "BrandNamer v2 build") */
    name: text("name"),

    /** pending → running → completed | failed | cancelled */
    status: text("status").notNull().default("pending"),

    /** Key of the phase currently executing (null if not started or finished) */
    currentPhaseKey: text("current_phase_key"),

    /**
     * Input context provided when the run started.
     * { specContent?: string, ideaContent?: string, brandContent?: string, params?: Record<string, unknown> }
     */
    inputContext: jsonb("input_context").$type<Record<string, unknown>>().notNull().default({}),

    /**
     * Skill plan generated by the skill planner after the blueprint phase.
     * Stored here so it persists across phases and survives crashes.
     * Same shape as skill-plan.json from Shaydee V3.
     */
    skillPlan: jsonb("skill_plan").$type<Record<string, unknown>>(),

    /**
     * Eval results gathered at the end of the run.
     * { scores: {}, patterns: {}, thresholdAdjustments: [] }
     */
    evalResults: jsonb("eval_results").$type<Record<string, unknown>>(),

    /** Agent that triggered/orchestrates the run (optional — can be system-triggered) */
    triggeredByAgentId: uuid("triggered_by_agent_id").references(() => agents.id, { onDelete: "set null" }),

    /** User who triggered the run (optional) */
    triggeredByUserId: uuid("triggered_by_user_id"),

    /** Source of the trigger */
    triggerSource: text("trigger_source").notNull().default("manual"),

    /** If this run is a retry of a previous run */
    retryOfRunId: uuid("retry_of_run_id").references((): AnyPgColumn => pipelineRuns.id, { onDelete: "set null" }),

    /** Counts of skill gate failures across all phases */
    totalSkillGateFailures: integer("total_skill_gate_failures").notNull().default(0),

    /** Counts of phase retries across all phases */
    totalRetries: integer("total_retries").notNull().default(0),

    error: text("error"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyStatusIdx: index("pipeline_runs_company_status_idx").on(table.companyId, table.status),
    companyTemplateIdx: index("pipeline_runs_company_template_idx").on(table.companyId, table.templateId),
    companyCreatedIdx: index("pipeline_runs_company_created_idx").on(table.companyId, table.createdAt),
  }),
);
